<?php
/**
 *Author: Katie Stinson
 *Date: 2/21/23
 *File: medical_student.class.php
 *Description: make medical student class
 */

class MedicalStudent extends GradStudent {

    //data members
    private $mcat;
    private static $student_count; //store num of students

    //constructor
    public function __construct($name, $gender, $major, $gpa, $program, $mcat)
    {
        parent::__construct($name, $gender, $major, $gpa, $program, $mcat);
        $this->mcat = $mcat;
        self::$student_count++;
    }

    //get methods
    public function getMcat(){
        return $this->mcat;
    }

    public static function getStudentCount(){
        return self::$student_count;
    }
    //set method
    public function setMcat($mcat){
        $this->mcat = $mcat;
    }
    //tostring method
    public function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo "<br /> MCAT: " . $this->getMcat();
    }

}